version: '3.8'

services:
  awr-web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPER_GROUP_ID=${SUPER_GROUP_ID}
      - WEB_APP_URL=${WEB_APP_URL:-http://localhost:5000}
      - SECRET_KEY=${SECRET_KEY:-awr-secret-key-change-me}
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-True}
    restart: unless-stopped
    
  awr-bot:
    build: .
    command: python bot.py
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPER_GROUP_ID=${SUPER_GROUP_ID}
      - WEB_APP_URL=${WEB_APP_URL:-http://localhost:5000}
    restart: unless-stopped
    depends_on:
      - awr-web

networks:
  default:
    name: awr-network